version: '3.7'
services:
  vault:
    image: hashicorp/vault:1.15.3
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    ports:
      - '8200:8200'
    volumes:
      - ./vault-data:/vault/data
  admin-service:
    build: ./admin_service
    environment:
      - VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}
      - VAULT_TOKEN=${VAULT_TOKEN:-root-token}
    ports:
      - '5000:5000'
    depends_on:
      - vault
    volumes:
      - ./admin_service/logs:/logs
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/mutual_tls.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - '8443:8443'
    depends_on:
      - admin-service
